region: us
version: '2'
authtoken: 3705tkJiSoF561qAfe2hQsSqj8s_3azM4R42Jebfqdx5WrWxE
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  plivo-app:
    addr: plivo-app:8002
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http